[mgr]
prepend_keymap = [
    { on = "<Up>", run = "arrow -1", description = "Previous task" },
    { on = "<Down>", run = "arrow 1", description = "Next task" },
    { on = "k", run = "arrow -1", description = "Previous task" },
    { on = "j", run = "arrow 1", description = "Next task" },
    { on = "<Space>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
    { on = "r",         run = "rename --hovered=no --cursor=end",  desc = "Rename selected file(s)" },
]
